format = "projects/v2"
id = "d605ea5e-4d6d-4a1e-93d8-7f35d08c656f"
name = "OSCP Lab Report"
language = "en-US"
tags = []
images = []

[[sections]]
id = "high-level_summary"
status = "in-progress"

[[sections]]
id = "appendix"
status = "in-progress"

[[sections]]
id = "coursexercises"
status = "in-progress"

[[sections]]
id = "methodology"
status = "in-progress"

[[sections]]
id = "other"
status = "in-progress"

[[sections]]
id = "Student"
status = "in-progress"

[report_data]
title = "OSCP Lab Report"
mail = "student@example.com"
osid = "XXXXX"
lastname = "Doe"
firstname = "John"
watermark = false
methodology = """
{{ report.firstname }} {{ report.lastname}} ({{ report.osid}}) utilized a widely adopted approach to perform penetration testing that is effective in testing how well the Offensive Security Labs and Exam environments are secure. Below is a breakout of how {{ report.firstname }} {{ report.lastname}} ({{ report.osid}}) was able to identify and exploit the variety of systems and includes all individual vulnerabilities found.

TODO Adapt as required
"""
penetration = """
The penetration testing portions of the assessment focus heavily on gaining access to a variety of systems. During this penetration test, {{ report.firstname }} {{ report.lastname}} ({{ report.osid}}) was able to successfully gain access to 10 out of the 50 systems.

TODO Adapt as required
"""
serviceenum = """
The service enumeration portion of a penetration test focuses on gathering information about what services are alive on a system or systems. This is valuable for an attacker as it provides detailed information on potential attack vectors into a system. Understanding what applications are running on the system gives an attacker needed information before performing the actual penetration test.  In some cases, some ports may not be listed.

TODO Adapt as required
"""
housecleaning = """
The house cleaning portions of the assessment ensures that remnants of the penetration test are removed. Often fragments of tools or user accounts are left on an organizations computer which can cause security issues down the road. Ensuring that we are meticulous and no remnants of our penetration test are left over is important.

After the trophies on both the lab network and exam network were completed, John removed all user accounts and passwords as well as the Meterpreter services installed on the system. Offensive Security should not have to remove any user accounts or services from the system.

TODO Adapt as required
"""
infogathering = """
The information gathering portion of a penetration test focuses on identifying the scope of the penetration test. During this penetration test, {{ report.firstname }} {{ report.lastname}} ({{ report.osid}}) was tasked with exploiting the lab and exam network. The specific IP addresses were:

**Lab Network:**

* System-1
* System-2
* etc.

TODO Adapt as required
"""
maintainaccess = """
Maintaining access to a system is important to us as attackers, ensuring that we can get back into a system after it has been exploited is invaluable. The maintaining access phase of the penetration test focuses on ensuring that once the focused attack has occurred (i.e. a buffer overflow), we have administrative access over the system again. Many exploits may only be exploitable once and we may never be able to get back into a system after we have already performed the exploit. 

{{ report.firstname }} {{ report.lastname}} ({{ report.osid}}) added administrator and root level accounts on all systems compromised. In addition to the administrative/root access, a Metasploit meterpreter service was installed on the machine to ensure that additional access could be established.

TODO Adapt as required
"""
report_version = "1.0"
recommendations = """
{{ report.firstname }} {{ report.lastname}} ({{ report.osid}}) recommends patching the vulnerabilities identified during the testing to ensure that an attacker cannot exploit these systems in the future. One thing to remember is that these systems require frequent patching and once patched, should remain on a regular patch program to protect additional vulnerabilities that are discovered at a later date.

TODO Adapt as required
"""
appendix_sections = []
highlevel_summary = """
{{ report.firstname }} {{ report.lastname}} ({{ report.osid}}) was tasked with performing an internal penetration test towards Offensive Security Labs. An internal penetration test is a dedicated attack against internally connected systems. The focus of this test is to perform attacks, similar to those of a hacker and attempt to infiltrate Offensive Security’s internal lab systems – the THINC.local domain. {{ report.firstname }} {{ report.lastname}}’s ({{ report.osid}}) overall objective was to evaluate the network, identify systems, and exploit flaws while reporting the findings back to Offensive Security.

When performing the internal penetration test, there were several alarming vulnerabilities that were identified on Offensive Security’s network. When performing the attacks, {{ report.firstname }} {{ report.lastname}} ({{ report.osid}}) was able to gain access to multiple machines, primarily due to outdated patches and poor security configurations.  During the testing, {{ report.firstname }} {{ report.lastname}} ({{ report.osid}}) had administrative level access to multiple systems. All systems were successfully exploited and access granted.

TODO Adapt summary as required
"""
objective = """
{{ report.firstname }} {{ report.lastname}} ({{ report.osid}}) was tasked with performing an internal penetration test towards Offensive Security Labs. An internal penetration test is a dedicated attack against internally connected systems. The focus of this test is to perform attacks, similar to those of a hacker and attempt to infiltrate Offensive Security’s internal lab systems – the THINC.local domain. {{ report.firstname }} {{ report.lastname}}’s ({{ report.osid}}) overall objective was to evaluate the network, identify systems, and exploit flaws while reporting the findings back to Offensive Security.

When performing the internal penetration test, there were several alarming vulnerabilities that were identified on Offensive Security’s network. When performing the attacks, {{ report.firstname }} {{ report.lastname}} ({{ report.osid}}) was able to gain access to multiple machines, primarily due to outdated patches and poor security configurations.  During the testing, {{ report.firstname }} {{ report.lastname}} ({{ report.osid}}) had administrative level access to multiple systems. All systems were successfully exploited and access granted.

TODO Adapt summary as required
"""
lab_network = """
Offensive Security Complete Guide machines (alpha and beta) may not be included in your lab report, they are for demonstration purposes only. 

For more information regarding the Bonus Points requirements, please visit the following URL: [https://help.offensive-security.com/hc/en-us/articles/360040165632-OSCP-Exam-Guide](https://help.offensive-security.com/hc/en-us/articles/360040165632-OSCP-Exam-Guide)

TODO Adapt as required
"""

[[report_data.exercises]]
description = "TODO Adapt as required"
caption = "TODO a.b.c.d Exercise (e.g. \"2.4.3.4 - Finding Files in Kali Linux\")"

[[findings]]
id = "4ca3f64c-9e30-4cbc-bdf1-e41a3402b25d"
status = "in-progress"

[findings.assignee]
id = "c01c7ccf-7597-45cc-99bb-01be93743b97"

[findings.data]
title = "Target #1"
cvss = "n/a"
ip_address = "TODO IP Address"
initialaccess = "TODO Describe initial access"
postexploitation = "TODO Describe Post Exploitation"
privilegeescalation = "TODO Describe privilege escalation"
serviceenum = """
**Port Scan Results**

| IP Address | Ports Open |
| ------- | ------- |
| TODO   | TODO **TCP:** **UDP:**

TODO
* `nmap -Pn -n 8.8.8.8 | grep open | cut -d/ -f1 | sed 'N;s/\\n/, /g'` for comma separated TCP ports
* `nmap -sU -Pn -n 8.8.8.8 | grep open | cut -d/ -f1 | sed 'N;s/\\n/, /g'` for comma separated UDP ports

**TODO further enumeration results**
"""

[project_type]
file = "../offsec-designs/oscp-lab.toml"
