format = "projecttypes/v2"
id = "431ca4e2-14f4-41bc-a431-07e8002b45de"
name = "OSDA Exam Report v1.2"
language = "en-US"
status = "finished"
tags = [
    "offsec",
    "OffensiveSecurity",
]
finding_ordering = []
default_notes = []
report_template = """
<div id="footer" data-sysreptor-generated="page-footer">
    <div id="footer-left"><em>CONFIDENTIAL</em></div>
    <div id="footer-center">{{ report.title }}</div>
</div>

<div v-if="report.watermark" id="watermark-osid">{{ report.osid }}</div>


<section id="page-cover" data-sysreptor-generated="page-cover">
    <div id="page-cover-background" />
    <div id="page-cover-title">
        <h1>Offensive Security</h1>
        <h2>{{ report.title }}</h2>
    </div>

    <div id="page-cover-student">
        <p id="page-cover-osid">
            <strong>OSID: {{ report.osid }}</strong><br>
            {{ report.mail }}<br>
        </p>
        <p id="page-cover-meta">
            {{ formatDate(report.report_date, 'long') }}<br>
            v{{ report.report_version }}
        </p>
    </div>
</section>
<pagebreak />


<table-of-contents id="toc" v-slot="tocItems">
    <h1>Table of Contents</h1>
    <ul>
        <li v-for="item in tocItems" :class="'toc-level' + item.level">
            <ref :to="item.id" />
        </li>
    </ul>
    <pagebreak />
</table-of-contents>

<markdown>
    # Offensive Security OSDA Exam Documentation {.in-toc.numbered}
    The Offensive Security Exam report contains all efforts that were conducted in order to pass the Offensive Security certification test. This report should contain all items that were used to pass the exam and it will be graded from a standpoint of correctness and fullness to all aspects of the exam. The purpose of this report is to ensure that the student has a full understanding of security detection methodologies as well as the technical knowledge to pass the qualifications for the Offensive Security Defense Analyst.

    ## Objective {.in-toc.numbered}
    The objective of this assessment is to perform detections and analysis on the simulated exam network in order to determine which attacker actions took place in each of the 10 phases.

    An example page has already been created for you at the latter portions of this document that should demonstrate the amount of information and detail that is expected in the exam report. Use the sample report as a guideline to get you through the reporting.

    ## Requirements {.in-toc.numbered}
    The student will be required to fill out this penetration testing report fully and to include the following sections:

    * Overall High-Level Summary of level of compromise
    * Detailed walkthrough of attacker actions in each phase
    * Each finding with included screenshots, explanations, event / log entries, and KQL queries if applicable
</markdown>
<pagebreak />

<section>
    <h1 id="summary" class="in-toc numbered">High-Level Summary</h1>
    <markdown :text="report.highlevel_summary" />
    <pagebreak />
</section>

<section>
    <h1 id="findings" class="in-toc numbered">Phases</h1>
    <div v-for="finding in findings">
        <h2 :id="finding.id" class="in-toc numbered">{{ finding.title }}</h2>
        <div v-for="step in finding.steps">
            <h3 class="in-toc numbered">{{ step.step_title }}</h3>
            <markdown :text="step.step_details" />
        </div>
        <pagebreak />
    </div>
</section>

<section v-if="report.appendix_sections.length > 0" class="appendix">
    <h1 id="appendix" class="in-toc numbered">Appendix</h1>

    <div v-for="appendix_section in report.appendix_sections">
        <h2 class="in-toc numbered">{{ appendix_section.title }}</h2>
        <markdown :text="appendix_section.content" />
    </div>
    <pagebreak />
</section>

<section>
    <div class="end-of-report">
        End of Report<br>
    </div>
    <div class="end-of-report">
        This report was rendered<br>
        by <a href="https://docs.sysreptor.com/">SysReptor</a> with<br>
        <span style="color:red;">&hearts;</span><br>
    </div>
</section>
"""
report_styles = """
@import "/assets/global/base.css";

/* Define variables */
:root {
    --color-risk-critical: #E83221;
    --color-risk-high: #FF9300;
    --color-risk-medium: #FFDA00;
    --color-risk-low: #4285F5;
    --color-risk-info: #00AE51;

    --color-cover-page-bg: #005ad0; 
}

/* Font settings */
html {
    font-family: "Noto Sans", sans-serif;
    font-size: 10pt;
}


/* Global styles */
@page {
    size: A4 portrait;
    margin: 35mm 20mm 25mm 20mm;
}

a {
    font-style: italic;
    text-decoration: none;
    color: inherit;
}

pre code {
    border: 1px solid black;
    padding: 0.2em !important;
}
code {
    background-color: rgb(221, 221, 221);
}


table {
    table-layout: fixed;
}
.markdown table {
    table-layout: auto;
}
th {
    background-color: #ABABAB;
    font-weight: bold;
}
tr.table-row-link td {
    padding: 0;
}
tr.table-row-link td a {
    display: block;
    padding: 0.3em;
    color: inherit;
    text-decoration: none;
    font-style: inherit;
}
.table-key {
    background-color: #ABABAB;
}


/* Classes for risk colors */
.risk-critical { color: var(--color-risk-critical) !important; font-weight: bold; }
.risk-high { color: var(--color-risk-high) !important; font-weight: bold; }
.risk-medium { color: var(--color-risk-medium) !important; font-weight: bold; }
.risk-low { color: var(--color-risk-low) !important; font-weight: bold; }
.risk-info { color: var(--color-risk-info) !important; font-weight: bold; }

.risk-bg-critical { background-color: var(--color-risk-critical) !important; color: white !important; }
.risk-bg-high { background-color: var(--color-risk-high) !important; }
.risk-bg-medium { background-color: var(--color-risk-medium) !important; }
.risk-bg-low { background-color: var(--color-risk-low) !important; }
.risk-bg-info { background-color: var(--color-risk-info) !important; }

/* Helper class for referencing page number */
.ref-page::before { 
    content: "" !important;
}
.ref-page::after {
    content: target-counter(attr(href), page) !important;
}
.ref-page .ref-title {
    display: none !important;
}

/* Table in finding chapters */
.finding-heading .table-key {
    height: 3em;
    width: 10em;
}


.end-of-report {
    text-align:center;
    font-style:italic;
    margin-top:70px;
    line-height:1.7;
}





/* #region footer */
@page {
    @bottom-left { content: element(footer-left); }
    @bottom-center { content: element(footer-center); }
    @bottom-right-corner { content: counter(page); }
}
#footer {
    position: absolute;
    width: 0;
}
#footer #footer-left { position: running(footer-left); }
#footer #footer-center { position: running(footer-center); }
/* #endregion footer */

/* #region watermark */
#watermark-osid {
    position: fixed;
    top: 9cm;
    left: 1cm;
    transform: rotate(-45deg);
    font-size: 90pt;
    text-transform: uppercase;
    opacity: 0.2;
}
/* #endregion watermark */

/* #region page-cover */
#page-cover {
    page: page-cover;
}
@page page-cover {
    /* Footer on the cover page */
    @bottom-right-corner {
        content: "";
    }
    @bottom-right {
        /* Page number */
        content: counter(page);
        font-size: 9pt;
        color: white
    }
    @bottom-left {
        content: "Confidential";
        text-transform: uppercase;
        font-style: italic;
        color: white;
    }
     /* Pentest title should not appear on cover page */
    @bottom-center {
        content: '';
    }
}
#page-cover-background {
    position: absolute;
    margin-top: -35mm;
    margin-left: -20mm;
    width: 210mm;
    height: 297mm;
    background-color: var(--color-cover-page-bg);
}
/* Title page elements */
#page-cover-title {
    position: absolute;
    top: 20mm;
    left: 0;
    width: 14cm;
    color: #ffffff;
}
#page-cover-title h1 {
    font-size: 32pt;
}
#page-cover-title h2 {
    font-size: 24pt;
}
#page-cover-student {
    position: absolute;
    top: 11cm;
    left: 0;
    width: 14cm;
    color: #ffffff;
}
#page-cover-osid {
    font-size: 14pt;
}
#page-cover-meta {
    line-height: 2em;
}
/* #endregion page-cover */

/* #region toc */
#toc li {
    list-style: none;
    margin: 0;
    padding: 0;
}
#toc .ref::before {
    padding-right: 0.5em;
}
#toc .ref::after {
    content: " " leader(".") " " target-counter(attr(href), page);
}
#toc .toc-level1 {
    font-size: 1.5rem;
    font-weight: bold;
    margin-top: 0.8rem;
}
#toc .toc-level2 {
    font-size: 1.2rem;
    font-weight: bold;
    margin-top: 0.5rem;
    margin-left: 2rem;
}
#toc .toc-level3 {
    font-size: 1rem;
    margin-top: 0.4rem;
    margin-left: 4rem;
}
#toc .toc-level4 {
    font-size: 1rem;
    margin-top: 0;
    margin-left: 6rem;
}
/* #endregion toc */
"""

[[report_sections]]
id = "Student"
label = "Student"

[[report_sections.fields]]
id = "firstname"
type = "string"
label = "Firstname"
origin = "custom"
default = "John"
required = true
spellcheck = false

[[report_sections.fields]]
id = "lastname"
type = "string"
label = "Lastname"
origin = "custom"
default = "Doe"
required = true
spellcheck = false

[[report_sections.fields]]
id = "osid"
type = "string"
label = "OSID"
origin = "custom"
default = "XXXXX"
required = true
spellcheck = false

[[report_sections.fields]]
id = "mail"
type = "string"
label = "Mail"
origin = "custom"
default = "student@example.com"
required = true
spellcheck = false

[[report_sections]]
id = "other"
label = "Document Control"

[[report_sections.fields]]
id = "title"
type = "string"
label = "Title"
origin = "core"
default = "OSDA Exam Documentation"
required = true
spellcheck = true

[[report_sections.fields]]
id = "report_date"
type = "date"
label = "Report Date"
origin = "custom"
required = true

[[report_sections.fields]]
id = "report_version"
type = "string"
label = "Report Version"
origin = "custom"
default = "1.0"
required = true
spellcheck = false

[[report_sections.fields]]
id = "watermark"
type = "boolean"
label = "Watermark"
origin = "custom"
default = false

[[report_sections]]
id = "highlevel_summary"
label = "High-Level Summary"

[[report_sections.fields]]
id = "highlevel_summary"
type = "markdown"
label = "High-Level Summary"
origin = "custom"
default = """
TODO This report details and documents the attacks observed against the Offensive Security OSDA exam network.

The attacker organization started by performing a brute force against an internet accessible RDP server called APPSRV02 and obtained administrative access. This led to a complete compromise of the server.

Next the attacker performed lateral movement to the internal server APPSRV02 by reusing stolen credentials from APPSRV02, this also led to a complete compromise of APPSRV03.

[…]
"""
required = true

[[report_sections]]
id = "appendix"
label = "Appendix"

[[report_sections.fields]]
id = "appendix_sections"
type = "list"
label = "Appendix"
origin = "custom"
required = true

[report_sections.fields.items]
id = ""
type = "object"
label = ""
origin = "custom"

[[report_sections.fields.items.properties]]
id = "title"
type = "string"
label = "Title"
origin = "custom"
default = "TODO appendix title"
required = true
spellcheck = false

[[report_sections.fields.items.properties]]
id = "content"
type = "markdown"
label = "Content"
origin = "custom"
default = "TODO This section is placed for any additional items that were not mentioned in the overall report."
required = true

[[finding_fields]]
id = "title"
type = "string"
label = "Phase"
origin = "core"
default = "TODO Phase Name"
required = true
spellcheck = true

[[finding_fields]]
id = "steps"
type = "list"
label = "Steps"
origin = "custom"
required = true

[finding_fields.items]
id = ""
type = "object"
label = ""
origin = "custom"

[[finding_fields.items.properties]]
id = "step_details"
type = "markdown"
label = "Step Details"
origin = "custom"
default = "TODO step details"
required = true

[[finding_fields.items.properties]]
id = "step_title"
type = "string"
label = "Step Title"
origin = "custom"
default = "TODO step title"
required = true
spellcheck = false

[report_preview_data]
[report_preview_data.report]
title = "OSDA Exam Documentation"
firstname = "John"
lastname = "Doe"
osid = "OS-XXXXX"
mail = "student@example.com"
report_date = "2022-07-29"
report_version = "1.0"
watermark = true
highlevel_summary = """
TODO This report details and documents the attacks observed against the Offensive Security OSDA exam network.

The attacker organization started by performing a brute force against an internet accessible RDP server called APPSRV02 and obtained administrative access. This led to a complete compromise of the server.

Next the attacker performed lateral movement to the internal server APPSRV02 by reusing stolen credentials from APPSRV02, this also led to a complete compromise of APPSRV03.

[…]
"""

[[report_preview_data.report.appendix_sections]]
title = "Appendix Title"
content = "Appendix content"

[[report_preview_data.findings]]
title = "Phase 1"
id = "90a0038a-3649-4a37-8151-06c935a5a15e"
created = "2024-12-09T13:11:25.791917+00:00"
order = 1

[[report_preview_data.findings.steps]]
step_details = """
The initial indicator of an attack happening was the triggering of a pre-defined threshold rule called “Possible RDP brute force” as shown below.

![](/assets/name/image-590869.png)

By looking at how the rule was defined, it is triggered by more than 100 instances of event ID 4625, which is a failed logon. This could align with a brute force attack where the attacker makes use of a user and/or password list.

When we inspect some of the events that triggered the alert, as shown below, we notice that the server reporting the events is APPSRV02.

![](/assets/name/image-127195.png)

Given that an attacker may have attempted to brute force the server, we should search for a subsequent successful log on event to APPSRV02 to determine if they obtained access.

We do this with the following KQL query:

event.code : "4624" and NOT user.name : SYSTEM and NOT user.name : DWM-2

From this query we find the following event entry:

![](/assets/name/image-322213.png)

This shows that the user Peter did a successful logon to APPSRV02 shortly after the suspected brute force attack. The source IP of the logon event was 192.168.67.69 which means its not a local logon, but remotely.

At this point we have a strong suspicion that the account with the username Peter was compromised and a malicious actor obtained access to APPSRV02 coming from the IP address 192.168.67.69. We should escalate this to an incident and contact the user to verify whether this was a legitimate logon.
"""
step_title = "RDP Brute Force"

[[report_preview_data.findings.steps]]
step_details = """
After suspicion of a compromise, additional investigation should be performed. One area is looking for persistence and a common way attackers employ is through the registry.

To try and determine if this happed, we can use the KQL query:

process.name : "reg.exe"
As a result, we find the following event:

![](/assets/name/image-781171.png)

This shows that a registry change was performed. An entry for the Run key was added. The Run registry key is used when a user logs on to the computer and thus is often used for persistence.

In particular we notice that the file “C:\\Windows\\System32\\update.exe” will be executed when a user logs on to APPSRV02.

We should escalate this to investigate what the file update.exe is.

"""
step_title = "Persistence"

[[report_preview_data.findings.steps]]
step_details = "In this phase we have strong suspicions that a malicious actor performed a brute force attack against APPSRV02 and managed to compromise the user account with the username “Peter”. Additionally, we suspect that persistence was set up through a Run key in the registry to execute the file “C:\\Windows\\System32\\update.exe”."
step_title = "Summary"

[[report_preview_data.findings]]
title = "Phase 2"
id = "8a39146e-3b2c-4d93-b1d7-9f604092fae4"
created = "2024-12-09T13:11:25.791979+00:00"
order = 2

[[report_preview_data.findings.steps]]
step_details = "TODO step details"
step_title = "TODO step title"

[[report_preview_data.findings]]
title = "Phase 3"
id = "7d3e1727-5993-44b8-b06c-89e97c3d35c0"
created = "2024-12-09T13:11:25.792015+00:00"
order = 3

[[report_preview_data.findings.steps]]
step_details = "TODO step details"
step_title = "TODO step title"

[[report_preview_data.findings]]
title = "Phase 4"
id = "489071b1-0a42-47ca-aa31-0b3f7e5260cd"
created = "2024-12-09T13:11:25.792047+00:00"
order = 4

[[report_preview_data.findings.steps]]
step_details = "TODO step details"
step_title = "TODO step title"

[[report_preview_data.findings]]
title = "Phase 5"
id = "cab9e74f-4735-4665-ad2f-f9a05ca84870"
created = "2024-12-09T13:11:25.792078+00:00"
order = 5

[[report_preview_data.findings.steps]]
step_details = "TODO step details"
step_title = "TODO step title"

[[report_preview_data.findings]]
title = "Phase 6"
id = "cba6456f-02f1-4ce0-9b1e-88f8bca06430"
created = "2024-12-09T13:11:25.792109+00:00"
order = 6

[[report_preview_data.findings.steps]]
step_details = "TODO step details"
step_title = "TODO step title"

[[report_preview_data.findings]]
title = "Phase 7"
id = "9e79526d-1c15-4eaa-8335-490e895053b0"
created = "2024-12-09T13:11:25.792140+00:00"
order = 7

[[report_preview_data.findings.steps]]
step_details = "TODO step details"
step_title = "TODO step title"

[[report_preview_data.findings]]
title = "Phase 8"
id = "9fb08d0f-f4f7-469c-9423-87bc6e6b25de"
created = "2024-12-09T13:11:25.792173+00:00"
order = 8

[[report_preview_data.findings.steps]]
step_details = "TODO step details"
step_title = "TODO step title"

[[report_preview_data.findings]]
title = "Phase 9"
id = "81d6959d-f7e7-4cab-a0e5-484107a4a534"
created = "2024-12-09T13:11:25.792204+00:00"
order = 9

[[report_preview_data.findings.steps]]
step_details = "TODO step details"
step_title = "TODO step title"

[[report_preview_data.findings]]
title = "Phase 10"
id = "2a5fd063-334a-4158-9ff9-a4735f556c51"
created = "2024-12-09T13:11:25.792235+00:00"
order = 10

[[report_preview_data.findings.steps]]
step_details = "TODO step details"
step_title = "TODO step title"
