site_name: "SysReptor"
site_url: "https://docs.sysreptor.com/"
repo_url: https://github.com/syslifters/sysreptor/
site_dir: ./site/ # Where to put the HTML files
nav:
  - Features and Pricing: features-and-pricing.md
  - Setup:
    - Installation: setup/installation.md
    - Configuration: setup/configuration.md
    - Setup Webserver: setup/webserver.md
    - Single Sign-On:
      - SSO Setup: setup/oidc-setup.md
      - Keycloak: setup/oidc-keycloak.md
      - Azure AD: setup/oidc-azure-active-directory.md
      - Google: setup/oidc-google.md
      - Generic: setup/oidc-generic.md
    - User Permissions: setup/user-permissions.md
    - Updates: setup/updates.md
    - Backups: setup/backups.md
  - Writing Reports:
    - Markdown Syntax: reporting/markdown-features.md
    - Spell Check: reporting/spell-check.md
    - References: reporting/references.md
    - Finding Templates: finding-templates/create-finding.md
    - Locked Sections: reporting/locking.md
  - Designing Reports:
      - Designer: designer/designer.md
      - Page Layout: designer/page-layout.md
      - Headings and ToC: designer/headings-and-table-of-contents.md
      - Tables: designer/tables.md
      - Figures: designer/figures.md
      - Footnotes: designer/footnotes.md
      - Charts: designer/charts.md
      - Design Guides: designer/design-guides.md
      - Formatting Utilities: designer/formatting-utils.md
      - Debugging: designer/debugging.md
      - FAQs: designer/faqs.md
  - Finding Templates: 
    - Overview: finding-templates/overview.md
    - Create Finding: finding-templates/create-finding.md
    - Multilingual: finding-templates/multilingual.md
  - Automize Reporting via CLI (alpha):
      - Getting Started: cli/getting-started.md
      - Setup: cli/setup.md
      - Tools:
        - Nmap: cli/tools/nmap.md
        - Nikto: cli/tools/nikto.md
        - ZAP: cli/tools/zap.md
        - SSLyze: cli/tools/sslyze.md
      - Uploads:
        - File: cli/uploads/file.md
        - Note: cli/uploads/note.md
      - Projects and Templates:
        - Projects: cli/projects/projects.md
        - Templates: cli/projects/templates.md
        - Translate: cli/projects/translate.md
      - Importers:
        - Ghostwriter: cli/importers/ghostwriter.md
      - Customization:
        - Tools: cli/customization/tools.md
      - Writing plugins:
        - Tools: cli/writing-plugins/tools.md
        - Importers: cli/writing-plugins/importers.md
  - Tech Insights:
    - Rendering Workflow: insights/rendering-workflow.md
    - Archiving: insights/archiving.md
    - Security Considerations: insights/security-considerations.md
  - Show and Tell: show-and-tell/index.md
  - OSCP Reporting: offsec-reporting-with-sysreptor.md
  - Contact Us: contact-us.md

    
theme:
  name: material
  custom_dir: overrides
  logo: images/logo.svg
  features:
    - content.code.annotate
    - search.share
  palette: 
    - scheme: default
  theme:
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/question-16

extra_css:
  - stylesheets/extra.css
  - stylesheets/hint.min.css

plugins:
  - blog:
      enabled: true
      blog_dir: show-and-tell
      archive: false
      categories: false
      post_readtime: false
  - social:
      enabled: !ENV [CI, true]
      cards: !ENV [CI, true]
      cards_color:
        fill: "#001827"
        text: "#F9FDFF"
      cards_font: Exo
  - tooltips
  - search
  - privacy:
      enabled: !ENV [CI, true]
  - redirects:
      redirect_maps:
        "setup/nginx-server.md": "setup/webserver.md"
        "reporting/referencing-sections.md": "reporting/references.md"
        "setup/prerequisites.md": "setup/installation.md"
        "backups.md": "setup/backups.md"
        "templates.md": "finding-templates/overview.md"
        "reporting/archiving.md": "insights/archiving.md"

markdown_extensions:
  - attr_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.magiclink
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.snippets:
      url_download: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true 
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sysreptor
    - icon: fontawesome/brands/linkedin
      link: https://at.linkedin.com/showcase/sysreptor
  generator: false

copyright: '<a href="https://www.syslifters.com/" target="_blank">Our Website</a> | <a href="https://www.syslifters.com/impressum" target="_blank">Imprint</a> | <a href="/data-privacy">Data Privacy</a> | <a href="/contact-us" target="blank">Contact</a><br><br>The FFG is the central national funding organization and strengthens Austria''s innovative power.<br>This project is funded by the <a href="https://www.ffg.at" target="_blank">FFG</a>.<br>'
